### ISSUE TITLE
Why not use nix?

### ISSUE THREAD

**Issue by Susurrus** [mneumann/errno-dragonfly-rs#1]
You might find it easier to use [nix](https://github.com/nix-rust/nix) rather than create and maintain your own small crate just for this functionality. We have an `errno_location()` function on DragonFlyBSD that calls into `__dfly_error()` and should work for your use case. If it doesn't, we'd be happy to integrate any necessary changes to get it working for you.

**Comment by mneumann** [comment]
@Susurrus Because __dfly_error() is wrong and does not work. This function does not exist anymore in the Rust code. Actually I added __dfly_error() long ago to the Rust source to make errno work on DragonFly, but as more and more code was migrated from C to Rust, this function has been removed. I think the nix crate now has merged my code (from this crate) into it.
